/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2024-01-27

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "main.h"




///////////////////////////////////////////
//globals
volatile uint32_t TimingDelay;

char buffer[32] = {0x00};
int size = 0;

int main(void)
{

    //Configure the systick with interrupts, HSI = 16Mhz
    if (SysTick_Config(SystemCoreClock / 1000))
    {
        while (1);
    }

    //configure the hardware
    gpio_init();
    gpio_button_init();

    usart2_init();
    spi1_init();

    LCD_Config();
    LCD_BacklightOn();
    LCD_Clear(0x00);

    //returns the status of the sdcard
    //value > 0 - Size of the directory file after it's built
    //value < 0 - negative value of the FR_RESULT code

    LCD_DrawStringKern(0, 3, "Init SDCard...");
    int result = SD_Init();

    if (result > 0)
    {
        size = snprintf(buffer, 32, "SD Res: %d", result);
        LCD_DrawStringKernLength(1, 3, (uint8_t*)buffer, size);
        size = snprintf(buffer, 32, "Dir Size: %d", result);
        LCD_DrawStringKernLength(2, 3, (uint8_t*)buffer, size);
    }
    else
    {
        //invalid / problem with initializing the sdcard
        LCD_DrawStringKern(1, 3, "SDCard Error...");
        size = snprintf(buffer, 32, "SD Res: %d", (-1)*result);
        LCD_DrawStringKernLength(2, 3, (uint8_t*)buffer, size);
    }

    LCD_DrawStringKern(4, 3, "Press Btn ...");

    while (!buttonFlag)
    {

    }

    buttonFlag = 0;

    //make a file
//    SD_FileCreate("counter.txt");
    char* msg = "This is the header in the counter file\r\n";
    SD_AppendData("counter.txt", msg, strlen(msg));

    volatile int counter = 0;

    /* Infinite loop */
    while (1)
    {
        LCD_Clear(0x00);
        LCD_DrawStringKern(0, 3, "HELLO LCD");

        LCD_DrawStringKern(2, 3, "Counter:");

        size = snprintf(buffer, 32, "Cnt: %d", counter);
        LCD_DrawStringKernLength(4, 3, (uint8_t*)buffer, size);

        //write the data to the sdcard, returns the number of
        //bytes written if ok, returns a negative result if an
        //error occured.
        size = snprintf(buffer, 32, "Cnt: %d\r\n", counter);
        int fres = SD_AppendData("counter.txt", buffer, size);

        if (fres > 0)
        {
            size = snprintf(buffer, 32, "Bytes: %d", fres);
            LCD_DrawStringKernLength(5, 3, (uint8_t*)buffer, size);

            //open it again, get the file size and output to the lcd
            uint32_t temp = 0;
            fres = SD_GetFileSize("counter.txt", &temp);

            LCD_DrawStringKern(6, 3, "Total Size:");
            size = snprintf(buffer, 32, "%d", temp);
            LCD_DrawStringKernLength(7, 3, (uint8_t*)buffer, size);

        }
        else        //error
        {
            size = snprintf(buffer, 32, "Error: %d", (-1)*fres);
            LCD_DrawStringKernLength(5, 3, (uint8_t*)buffer, size);
        }


        counter++;

        //read the buttonFlag
        if (buttonFlag == 1)
        {
            usart2_txString("Hello from program\r\n");

            buttonFlag = 0;
        }

        Delay(1000);
//        GPIO_ToggleBits(GPIOA, GPIO_Pin_5);


    }
}



/////////////////////////////////////////////////
//Delay
void Delay(volatile uint32_t timeTick)
{
    TimingDelay = timeTick;
    while (TimingDelay != 0);
}


////////////////////////////////////////////////
void TimingDelay_Decrement(void)
{
    if (TimingDelay != 0)
        TimingDelay--;
}



