/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2024-01-27

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include <stdint.h>
#include <string.h>

#include "main.h"




///////////////////////////////////////////
//globals
volatile uint32_t TimingDelay;

char buffer[64] = {0x00};
int size = 0;

int main(void)
{
    //configure the system clock
    //use HSI clock 16mhz.  want to config the system to run at 100mhz,
    //HAL uses the following values:
//    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
//      RCC_OscInitStruct.HSIState = RCC_HSI_ON;
//      RCC_OscInitStruct.HSICalibrationValue = 16;
//      RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
//      RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
//      RCC_OscInitStruct.PLL.PLLM = 8;
//      RCC_OscInitStruct.PLL.PLLN = 100;
//      RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
//      RCC_OscInitStruct.PLL.PLLQ = 4;
    //SystemClockConfig(uint32_t PLL_M, uint32_t PLL_N, uint32_t PLL_P, uint32_t PLL_Q, uint32_t PLL_R);
    //the parameter R - not available on F411 - so might cause an error
   // SystemClockConfig(8, 100, 2, 4);

    //Configure the systick with interrupts, HSI = 16Mhz
    if (SysTick_Config(SystemCoreClock / 1000))
    {
        while (1);
    }

    //configure the hardware
    gpio_init();
    gpio_button_init();
    adc_init();         //pa1 - adc1 ch1 - need to configure PA1 as alternate function
    usart2_init();
    spi1_init();

    LCD_Config();
    LCD_BacklightOn();
    LCD_Clear(0x00);

    //returns the status of the sdcard
    //value > 0 - Size of the directory file after it's built
    //value < 0 - negative value of the FR_RESULT code

    LCD_DrawStringKern(0, 3, "Init SDCard...");
    int result = SD_Init();

    if (result > 0)
    {
        size = snprintf(buffer, 32, "SD Res: %d", result);
        LCD_DrawStringKernLength(1, 3, (uint8_t*)buffer, size);
        size = snprintf(buffer, 32, "Dir Size: %d", result);
        LCD_DrawStringKernLength(2, 3, (uint8_t*)buffer, size);
    }
    else
    {
        //invalid / problem with initializing the sdcard
        LCD_DrawStringKern(1, 3, "SDCard Error...");
        size = snprintf(buffer, 32, "SD Res: %d", (-1)*result);
        LCD_DrawStringKernLength(2, 3, (uint8_t*)buffer, size);
    }

    LCD_DrawStringKern(4, 3, "Press Btn ...");


    //make a file
    SD_FileCreate("counter.txt");
    char* msg = "This is the header in the counter file\r\n";
    SD_AppendData("counter.txt", msg, strlen(msg));

    /* Infinite loop */
    while (1)
    {
        LCD_Clear(0x00);
        LCD_DrawStringKern(0, 3, "Hell0 LCD");

        //output the adc from the dma buffer and the register directly
        size = snprintf(buffer, 32, "ADC1: %d", adc_getValueFromDMA());
        LCD_DrawStringKernLength(2, 3, (uint8_t*)buffer, size);

        size = snprintf(buffer, 32, "ADC-DR: %d", (uint16_t)ADC1->DR);
        LCD_DrawStringKernLength(3, 3, (uint8_t*)buffer, size);

        size = snprintf(buffer, 32, "OverRun: %d", adc_getError());
        LCD_DrawStringKernLength(4, 3, (uint8_t*)buffer, size);

        //read the buttonFlag
        if (buttonFlag == 1)
        {
            //do something
            gpio_shieldLedToggle();
            buttonFlag = 0;
        }

        gpio_shieldLedToggle();

        Delay(1000);

    }
}



/////////////////////////////////////////////////
//Delay
void Delay(volatile uint32_t timeTick)
{
    TimingDelay = timeTick;
    while (TimingDelay != 0);
}


////////////////////////////////////////////////
void TimingDelay_Decrement(void)
{
    if (TimingDelay != 0)
        TimingDelay--;
}


/////////////////////////////////////////////////
//Configures the system core clock to run with the
//PLL.
void SystemClockConfig(uint32_t PLL_M, uint32_t PLL_N, uint32_t PLL_P, uint32_t PLL_Q)
{
    volatile uint16_t timeout;

    RCC->CR |= RCC_CR_HSION;                            //enable the HSI clock

    timeout = 0xFFFF;
    while (!(RCC->CR & RCC_CR_HSIRDY) && timeout--);    //wait until the HSI clock is ready

    RCC->CFGR = (RCC->CFGR & ~(RCC_CFGR_SW)) | RCC_CFGR_SW_HSI;     //set HSI clock as the main clock

    RCC->CR &= ~RCC_CR_PLLON;           //make sure the PLL is off

    //load the PLL settings into the PLLCFG register
    RCC->PLLCFGR = (RCC->PLLCFGR & ~RCC_PLLM_MASK) | ((PLL_M << RCC_PLLM_POS) & RCC_PLLM_MASK);
    RCC->PLLCFGR = (RCC->PLLCFGR & ~RCC_PLLN_MASK) | ((PLL_N << RCC_PLLN_POS) & RCC_PLLN_MASK);
    RCC->PLLCFGR = (RCC->PLLCFGR & ~RCC_PLLP_MASK) | ((((PLL_P >> 1) - 1) << RCC_PLLP_POS) & RCC_PLLP_MASK);
    RCC->PLLCFGR = (RCC->PLLCFGR & ~RCC_PLLQ_MASK) | ((PLL_Q << RCC_PLLQ_POS) & RCC_PLLQ_MASK);

    RCC->CR |= RCC_CR_PLLON;            //enable the PLL

    //wait for the PLL to start
    timeout = 0xFFFF;
    while ((!(RCC->CR & RCC_CR_PLLRDY)) && timeout--);

    //set the PLL as the main clock
    RCC->CFGR = (RCC->CFGR & ~(RCC_CFGR_SW)) | RCC_CFGR_SW_PLL;

    //update the system core clock
    SystemCoreClockUpdate();
}


